# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='c1', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
