# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
