# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160212_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='que_array',
            field=models.TextField(default='', null=True),
        ),
    ]
