# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20160213_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='c1', max_length=200),
        ),
    ]
