# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='ans_array',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='atmpt_array',
            field=models.TextField(default='', null=True),
        ),
    ]
