# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20160625_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
