# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20170120_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='question',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
