# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20170120_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Test'),
        ),
    ]
