# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20170120_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='association',
            old_name='test',
            new_name='test_id',
        ),
    ]
