# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20170120_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='association',
            old_name='test_id',
            new_name='test',
        ),
    ]
