# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20170124_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTest',
            new_name='UsersTest',
        ),
    ]
