# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20170124_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='ongoing_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstest',
            name='test_progress',
            field=models.TextField(default='', null=True),
        ),
    ]
