# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20170124_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
