# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='ongoing_test',
            field=models.IntegerField(default=0),
        ),
    ]
