# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20170125_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstest',
            name='test_submitted',
            field=models.IntegerField(default=0),
        ),
    ]
